### ISSUE TITLE
runtime error: slice bounds out of range [:32] with capacity 0

### ISSUE THREAD

**Issue by luckman212** [blacs30/bitwarden-alfred-workflow#53]
Not sure what's causing this but since updating to 2.2.x I'm getting this error when trying to copy a password

`runtime error: slice bounds out of range [:32] with capacity 0`

I tried deleting my cache and refreshing, but no go...

**Comment by luckman212** [comment]
Not sure if it's related at all, but I noticed also that the cache clear / sync process seems to loop 2x for each run now. Is that normal?

```
17:14:57 BW DataPath /Users/luke/Library/Application Support/Bitwarden CLI/data.json
🍺
17:14:57 ----------- /2.2.0 (AwGo/0.26.2) -----------
17:14:57 &main.options{Search:false, Config:false, SetConfigs:false, Auth:false, Sfa:false, Lock:false, Icons:false, Folder:false, Unlock:false, Login:false, Logout:false, Sync:true, Open:false, GetItem:false, Force:false, Totp:false, Last:false, Cache:false, Background:false, Id:"", Query:"", Attachment:"", Output:""}
17:14:59 Clearing items cache.
Synced.
17:14:59 Read latest items...
17:15:00 Read latest folders...
17:15:01 Clearing items cache.
17:15:02 Background? false
17:15:02 Running cache
17:15:02 Read latest items...
17:15:03 Read latest folders...
17:15:04 ------------------ 6.877314808s ------------------
```

**Comment by blacs30** [comment]
Thanks for creating this bug.
The 2 things are unrelated, however the first issue is caused by the decryption of the secrets directly from the file. I assume it happens then for any other secret type like secret not, credit card number etc.
I will see what’s the issue and try to fix it soon.

**Comment by luckman212** [comment]
Thanks @blacs30 I will check if it also happens with other item types eg card data.

**Comment by luckman212** [comment]
Just confirming that yes I am hitting this error on all types including login, card, note...

**Comment by blacs30** [comment]
I didn't expect anything else.

[Bitwarden v2 2.2.1-fix.alfredworkflow.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5469289/Bitwarden.v2.2.2.1-fix.alfredworkflow.zip)

Could you please try that version. It doesn't really fix the issue with the decryption but it logs better (new workflow var "DEBUG" is set to true)
No secrets are logged but different lengths of the different keys and strings which are used for the decryption.
I've tested it with on 1 macs 2 different bitwarden users which are from bitwarden.com, no issues.

Are you running Bitwarden selfhosted?

I've also added hopefully all checks and error handling so that in the case an errors occurs the fallback (bitwarden cli) is used to get the secret.

Could you please also post the [DEBUG] output here. It should be most of it at the very end of the workflow output. Similar to that:

```
16:01:50 bitwarden.go:235: Getting item for id 0084fbe3-24e0-4502-a1c7-ac0e008eacdb
16:01:50 utils.go:154: [DEBUG] base64 decode protected key
[...]
```

Additionally to that, the very first line of the output looks this:

```
utils.go:154: [DEBUG] bwDataPath is: /Users/myuser/Library/Application Support/Bitwarden CLI/data.json
```

Can you please check if that file exist and if the following entries exist and look similar:

```
example data:
{
"__PROTECTED__key": "Bu29NYchhqcFdum/6/1ccVYDYvsrLtb4cKwBv0TK5Nu251LCAcaC/jg5yO8rNoOFOyW4C/cRsmbpGoFWpEreVG7X+ffRFUNukitoiKwMgmCPDM9lObeFN018CVofZNqt4A==",
(you should be able to base64 decode it)
"userId": "e62ac0b1-5763-4e08-ba66-ee043a95c91b",
(normal UUID format)
"encKey": "2.XViiDbPxHxXUR4C4r13OvA==|xkvTgQK0QrpqzzXo7RKBZsLyFyEiAPRGlsDcbffZWi4/8g+HFPoT5fXzSvuGrRC6NatMEI3qmIV/GmqRCh2n67wHWq+i4QKpXOT8IFsHBv4=|XZDpAPgtAerBG9y60HYveRh/696nXaQDvN7GslMMz4I="
(first digit, then a dot `.` then 3 groups devided by pipe `|`)
[...]
}

```

**Comment by luckman212** [comment]
@blacs30 sorry for the late reply, I missed this somehow. Testing now...

**Comment by luckman212** [comment]
@blacs30 Ok this is a little strange. The test workflow above works fine for me (no errors). I swapped back and forth between this and the updated one I've been working on in #49. For some reason, simply dragging the `bitwarden-alfred-workflow` go binary from this one into my version fixes the problem. So something is different about that one for sure, but I'm not able to peek into what.

> _Are you running Bitwarden selfhosted?_

**No**

> _are you in an organisation?_

**Yes** (but it's my own and there are currently no items in the Org vault)

Here's the bottom of the output from the Alfred console on a successful run just now with this debug version where I copied a password:
```
16:55:08 workflow.go:328: ----- Bitwarden v2/2.2.1-test3 (AwGo/0.26.2) -----
16:55:08 main.go:149: &main.options{Search:false, Config:false, SetConfigs:false, Auth:false, Sfa:false, Lock:false, Icons:false, Folder:false, Unlock:false, Login:false, Logout:false, Sync:false, Open:false, GetItem:true, Force:false, Totp:false, Last:false, Cache:false, Background:false, Id:"e6c717c1-7f6e-4d60-895b-aaf6014be603", Query:"login.password", Attachment:"", Output:""}
16:55:08 main.go:151: args=[]string{"-getitem", "-id", "e6c717c1-7f6e-4d60-895b-aaf6014be603", "login.password"} => []string{"login.password"}
16:55:08 main.go:152: (main.config) {
 AutoFetchIconCacheAge: (int) 1440,
 AutoFetchIconMaxCacheAge: (time.Duration) 24h0m0s,
 BwconfKeyword: (string) (len=9) ".bwconfig",
 BwauthKeyword: (string) (len=7) ".bwauth",
 BwKeyword: (string) (len=2) "bw",
 BwfKeyword: (string) (len=4) ".bwf",
 BwExec: (string) (len=2) "bw",
 BwDataPath: (string) "",
 CacheAge: (int) 7200,
 Debug: (bool) true,
 Email: (string) (len=22) "xxxxx@gmail.com",
 EmptyDetailResults: (bool) false,
 IconCacheAge: (int) 43200,
 IconCacheEnabled: (bool) true,
 IconMaxCacheAge: (time.Duration) 720h0m0s,
 MaxResults: (int) 1000,
 MaxCacheAge: (time.Duration) 120h0m0s,
 Mod1: (string) (len=3) "alt",
 Mod1Action: (string) (len=13) "username,code",
 Mod2: (string) (len=5) "shift",
 Mod2Action: (string) (len=3) "url",
 Mod3: (string) (len=4) "ctrl",
 Mod3Action: (string) (len=4) "totp",
 Mod4: (string) (len=7) "cmd,opt",
 Mod4Action: (string) (len=4) "more",
 NoModAction: (string) (len=13) "password,card",
 OutputFolder: (string) (len=22) "/Users/luke/Downloads/",
 Path: (string) (len=78) "/Users/luke/n/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
 ReorderingDisabled: (bool) true,
 Server: (string) (len=21) "https://bitwarden.com",
 Sfa: (bool) false,
 SfaMode: (int) 0,
 SyncCacheAge: (int) 7200,
 SyncMaxCacheAge: (time.Duration) 120h0m0s,
 TitleWithUser: (bool) true
}
16:55:08 bitwarden.go:235: Getting item for id e6c717c1-7f6e-4d60-895b-aaf6014be603
16:55:08 utils.go:154: [DEBUG] base64 decode protected key
16:55:08 utils.go:154: [DEBUG] protected Key length is: 97
16:55:08 utils.go:154: [DEBUG] protected Key encryption type is: 2
16:55:08 utils.go:154: [DEBUG] base64 decode session key
16:55:08 utils.go:154: [DEBUG] Session key length is: 64
16:55:08 utils.go:154: [DEBUG] comparing session mac with protected key
16:55:08 utils.go:154: [DEBUG] making the source key
16:55:08 utils.go:154: [DEBUG] making intermediate keys
16:55:08 utils.go:154: [DEBUG] decrypting final encryption keys
16:55:08 bitwarden.go:238: Error making source key is:
error decrypting key, encryption type not supported 0
16:55:08 bitwarden.go:266: MAC doesn't match brdvYuvfWW/aZU4frg02AquMIugFClwnqbTDpED2a6U= SM6bkhnVOPlSAmqSAzhWSX0plt2sSOIExHmKqsE2zUo=
16:55:09 bitwarden.go:321: Received key is: Te*
16:55:09 workflow.go:405: ------------------ 647.437515ms ------------------
[16:55:09.368] Bitwarden v2[Run Script] Processing complete
[16:55:09.369] Bitwarden v2[Run Script] Passing output 'Test9876' to Copy to Clipboard
[16:55:09.369] Bitwarden v2[Run Script] Passing output 'Test9876' to Arg and Vars
[16:55:09.370] Bitwarden v2[Arg and Vars] Processing complete
[16:55:09.371] Bitwarden v2[Arg and Vars] Passing output 'Copy Password for user:
xxxxx@xxxxx' to Post Notification
```

One other thing, I noticed here (screenshot) that the JSON is truncated - not sure if that's Alfred doing the truncating or if there's a problem with the process, but I haven't seen that before. Also, I noticed the `bwDataPath` you mentioned, that in the first part it prints a path (yes that path exists & is valid JSON) but lower down it's null... (`""`) not sure if that means anything...I assume it's just because I haven't overridden the `BW_DATA_PATH` env var...

![image](https://user-images.githubusercontent.com/1992842/98045990-61cec300-1df7-11eb-8d66-15ca4fa3e17f.png)

**Comment by blacs30** [comment]
@luckman212 thanks a lot for your feedback, that will help a lot I believe.
> I assume it's just because I haven't overridden the BW_DATA_PATH env var...

correct, since it's not overridden it defaults to the standard path.

Also the error message helps me much:
```
16:55:08 bitwarden.go:238: Error making source key is:
error decrypting key, encryption type not supported 0
```
That is where I need to continue..

Regarding the `[truncated]`, this is also normal for me, with more than 400 secrets. It's probably cut off because too long.

> The test workflow above works fine for me (no errors).

So that means you get your secret as expected? (it's just not as fast as it could be because I catch the error first and use the normal way via bitwarden cli command`bw get item <id>` )

**Comment by luckman212** [comment]
> _So that means you get your secret as expected? (it's just not as fast as it could be_

Yes - slowly but surely 🙂

**Comment by luckman212** [comment]
@blacs30 anything I can do to help debug?

**Comment by blacs30** [comment]
Unfortunately I didn't have time yet to look more into this.
The next steps which I plan to do:
- create a self hosted Bitwarden instance with docker and create an organisation to test the decryption with org secrets
- implement decryption for other [encryption types](https://github.com/bitwarden/browser/blob/f1262147a33f302b5e569f13f56739f05bbec362/src/services/constantsService.js#L13-L21)

I am not sure how to "force" the secrets to use a specific encryption type, if that would be known it would be easier to implement and test changes.

**Comment by blacs30** [comment]
@luckman212 ,
I've made some changes to the decrypt functions, possible it's working now also for keys with encryption type 0.
Would be great if you could try it out once more and paste the logs in case it's still failing.
I've used test4 auto sync version.

[Bitwarden.v2.2.1-test4-decryptfix.alfredworkflow.zip](https://github.com/blacs30/bitwarden-alfred-workflow/files/5527769/Bitwarden.v2.2.1-test4-decryptfix.alfredworkflow.zip)

**Comment by luckman212** [comment]
Thanks for this! I will test.  I was going to post some findings earlier but got busy on some other stuff. I'll send some better details tomorrow, but I've been playing around with https://github.com/attie/bitwarden-decrypt and it definitely works on my encrypted json.

I noticed that my KDF iterations were set to 5000 and the recommended is >100000 now. So I raised that setting and re-encrypted my vault. Not sure if that was the solution but I am able to get fast decryption from your tool now most of the time. I think there are some edge cases still or something that causes it to break but I am still trying to figure out exactly what's happening there.

**Comment by luckman212** [comment]
Also I will have to go back to some earlier backups, but I believe all my logins are now "type 2" aka `AesCbc256_HmacSha256_B64`. I don't know if this is a function of me re-encrypting my vault or--?

**Comment by blacs30** [comment]
> Also I will have to go back to some earlier backups to confirm, but I believe all my logins are now "type 2" aka `AesCbc256_HmacSha256_B64`. I don't know if this is a function of me re-encrypting my vault or--?

I think I read somewhere that type 0 `AesCbc256_B64` was legacy/originally used. But when re-encrypting or setting up a new account it uses type 2.

**Comment by luckman212** [comment]
> I read somewhere that type 0 AesCbc256_B64 was legacy/originally used

@blacs30 That makes sense—I've been a bitwarden user since nearly the beginning.

I uploaded a newer version of the workflow to #49 with the `-L` flag on L148 and it seems to work for both symlinked and non-symlinked workflows. Thanks for that tip.

The latest version of `./bitwarden-alfred-workflow` is mostly working for me, but I am facing issues, not sure if you can give any insight:

- as long as I perform all login/unlock/password retreival functions from ONLY using the Alfred workflow, everything is happy

- if I do anything _outside_ of that (using `bw` cli or the Electron app), the token gets invalidated and the workflow starts failing

- at this point, even though `Unexpected error. Exit code -1.` is output when trying to copy passwords, the "**success**" notification is presented by the workflow.

- to get it working again, I have to run `.bwauth unlock` again.  Then this invalidates the bw cli however.  So it's a tail chaser.

here's the debug output _after_ running `bw unlock` using the **bw CLI** and then trying to fetch a password via the Alfred workflow:

```
10:41:01 Getting item for id 8236c36f-e651-4eae-9075-a95300e560a3
10:41:01 [DEBUG] base64 decode protected key
10:41:01 [DEBUG] protected Key length is: 97
10:41:01 [DEBUG] protected Key encryption type is: 2
10:41:01 [DEBUG] base64 decode session key
10:41:01 [DEBUG] Session key length is: 64
10:41:01 [DEBUG] comparing session mac with protected key
10:41:01 MAC doesn't match xxxxxxxxxxxxxx= yyyyyyyyyyyyyy= [redacted]
10:41:01 Error making source key is:
MACs don't match of protectedkey and session key
10:41:01 [DEBUG] cs.encryptionType 2
10:41:01 crypto/aes: invalid key size 0
10:41:01 Error is:
Unexpected error. Exit code -1.
Unexpected error. Exit code -1.10:41:01 [ERROR] Unexpected error. Exit code -1.
```

my very uninformed guess as to what's happening:

- the `GetToken()` function in token.go refers to a `com.lisowski-development.alfred.bitwarden/token` stored in the macOS keychain
- this token is generated and handed down by the Bitwarden server, and refreshed during login/unlock functions
- the `bw` CLI has manages its own tokens (not in the keychain, I believe in the `__PROTECTED__key` value inside `~/Library/Application Support/Bitwarden CLI/data.json`)
- only 1 token can be valid at any given time(?)
- so it's a ping-pong of authorizations

If this is correct, is there a way to share the tokens somehow so a login from bw cli doesn't invalidate the Alfred workflow authorization?

**Comment by luckman212** [comment]
@blacs30 one last comment, in case you want to play around with [attie/bitwarden-decrypt](https://github.com/attie/bitwarden-decrypt), I [forked it](https://github.com/luckman212/bitwarden-decrypt) and made a couple of changes so it works on macOS. Might save you a few min. The project is in python3, but the process for decryption should be essentially the same so it might be useful... 🤷‍♂️ 

```
git clone https://github.com/luckman212/bitwarden-decrypt.git
cd bitwarden-decrypt
mkvirtualenv bitwarden-decrypt
pip install -r requirements.txt

./demo.py
(enter your bw master password...)
```

**Comment by luckman212** [comment]
Hey @blacs30 👋 
I played around with the auth tokens and figured out a way to make them play nice with each other. I only tested it minimally but I think this could be useful... see → [luckman212/bitwarden-cli-helpers](https://github.com/luckman212/bitwarden-cli-helpers)

With these helper functions in `.bash_profile` (or `.zshrc` if that's your thing) you can pass auth tokens back and forth between your Workflow and the `bw` CLI without invalidating the other session key.

Let me know what you think. Hopefully we can close up this issue and #49 if everything's happy. Things have been working pretty well for me using 2.2.1-test5.

**Comment by blacs30** [comment]
@luckman212 thanks a lot for all your comments.

Your observations were correct (I don't use the bw cli that often therefore I didn't run into that issue.)

Very nice script which you have there. If you don't mind we can link it in the README with a small description of the issue?

I noticed from your logs and also my own that the workflow is doing the expected:

If the decryption process (using the bitwarden data.json) fails then it falls back to the bitwarden cli.
Having this confirmed I am not going ahead and spend more time on getting the old encryption type working as the workflow would fall back to the bitwarden cli, which can handle it. I will however put a note into the README that a re-encryption would offer faster encryption. 

I'm also going to update the error regarding the ping-pong issue.

I will print the error from the bitwarden cli, it looks then this way which might give a hint in the right direction:

```
Unexpected error. Exit code -1. Has the session key changed?
[ERROR]  mac failed. ? Master password: [input is hidden] [37D[37C
```

**Comment by luckman212** [comment]
Yes of course, please feel free to copy or link to my scripts! I haven't been having any decryption problems since these last few rounds of changes and discovery. In fact I've even added a couple of Organizations to my Vault and they are also working fine.

Bravo again 👏 on your workflow - it is so incredibly useful and so much faster than opening up the very slow official BW app (Electron, ugh)

**Comment by eduwass** [comment]
Shouldn't this be added to the release file? I was having this problem but it was fixed after I applied [2.2.1-test5-fixdecrypt](https://github.com/blacs30/bitwarden-alfred-workflow/files/5532468/Bitwarden-2.2.1-test5-fixdecrypt.alfredworkflow.zip) as suggested in #63 

Anyways glad I found these issues here and was able to get it working.

Thanks for the work, great workflow!

**Comment by blacs30** [comment]
@eduwass the next release will include this fix. Glad you were able to find this issue and I'm sorry for the inconvenience.

**Comment by eduwass** [comment]
Hey @blacs30 , no problem thanks for letting me know!

**Comment by divmain** [comment]
The 2.2.1-test5-fixdecrypt prerelease didn't fix this for me.  Instead of seeing `runtime error: slice bounds out of range [:32] with capacity 0` it now copies `runtime error: slice bounds out of range [:-102]` into the clipboard.  Happy to help troubleshoot.

**Comment by blacs30** [comment]
@divmain thanks for reporting this. Strange that this happens, in case of an error it should fall back to the normal `bw get item` way.
Have you been using bitwarden already for a long time? then it might be the easiest to [update the encryption key](https://bitwarden.com/help/article/update-encryption-key/)

If you want to debug and post logs you can set the workflow environment variable `DEBUG` to `true` (create it if it doesn't exist), then in Alfred select the Bitwarden workflow and enable the debug console. 
Then run the workflow and try to get a secret.
The last 20-30 lines are debug output of the decryption functions. Secrets are not written to debug logs.

**Comment by divmain** [comment]
This resolved it for me!  Yes, I am a long-time BitWarden user and, although BW didn't notify me that I should update my encryption key, doing so manually resolved the issue.

Thanks for the tip!

For anyone encountering this issue in the future, the [linked doc](https://bitwarden.com/help/article/update-encryption-key/) doesn't specify how to force creation of a new key.  It's easy though:

- Login to your valut.
- Click Settings at the top of the page.
- Under My Account, scroll down to Encryption Key Settings.
- Follow the instructions provided.
- Logout (and on again) from Bitwarden on all devices.

**Comment by blacs30** [comment]
@divmain  I have taken over your steps and added them to the README.
